name: Build and Release Rust Project

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Rust
      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          components: rustfmt, clippy

      # Cache Cargo dependencies to speed up builds
      - name: Cache Cargo registry
        uses: actions/cache@v3
        with:
          path: ~/.cargo/registry
          key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-registry-

      - name: Cache Cargo build
        uses: actions/cache@v3
        with:
          path: ~/.cargo/bin
          key: ${{ runner.os }}-cargo-bin-${{ hashFiles('**/Cargo.toml') }}
          restore-keys: |
            ${{ runner.os }}-cargo-bin-

      # Build the project
      - name: Build project
        run: cargo build --release

      # Run tests (optional but recommended)
      - name: Run tests
        run: cargo test --release

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      # Check out the repository again
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Rust again for the release job
      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          components: rustfmt, clippy

      # Create a GitHub Release
      - name: Create GitHub release
        id: create_release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: target/release/guess-game

      # Upload the release asset
      - name: Upload release asset
        uses: softprops/action-gh-release@v1
        with:
          files: target/release/guess-game
